name: Build Amplify4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build Xcode project
      run: |
        xcodebuild -project Amplify4.xcodeproj -scheme Amplify4 -configuration Release
    - name: Archive output
      run: |
        mkdir -p dist
        cp -R build/Release/Amplify4.app dist/
        ditto -c -k --sequesterRsrc --keepParent dist/Amplify4.app Amplify4.zip
    - uses: actions/upload-artifact@v3
      with:
        name: Amplify4
        path: Amplify4.zip
